spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stc
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
