package com.stc;

import com.stc.entity.AppRole;
import com.stc.entity.ServiceUser;
import com.stc.security.service.UserService;
import com.stc.service.ItemService;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
//import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
//import org.springframework.security.crypto.password.PasswordEncoder;

@SpringBootApplication
@EnableJpaRepositories
public class StcAssessmentApplication {

    public static void main(String[] args) {
        SpringApplication.run(StcAssessmentApplication.class, args);
    }

//    @Bean
//    PasswordEncoder passwordEncoder() {
//        return new BCryptPasswordEncoder();
//    }

    //for test sample users generated by classLoader on run
//    @Bean
//    CommandLineRunner run(UserService userService, ItemService itemService) {
//        return args -> {
//
//            userService.saveRole(new AppRole().builder().name("ROLE_USER").build());
//            userService.saveRole(new AppRole().builder().name("ROLE_ADMIN").build());
//            userService.saveRole(new AppRole().builder().name("ROLE_OWNER").build());
//
//            userService.saveUser(new ServiceUser().builder().userEmail("java@stc.com").password("D@ner@#!#ADS_#@").build());
//            userService.saveUser(new ServiceUser().builder().userEmail("angular@stc.com").password("Asd&*@#!#ADS_#@").build());
//            userService.saveUser(new ServiceUser().builder().userEmail("devOpps@stc.com").password("IOP@#!#ADS_#@").build());
//
//            userService.addRoleToUser("stcAdmin", "ROLE_ADMIN");
//            userService.addRoleToUser("stcOwner", "ROLE_OWNER");
//            userService.addRoleToUser("stcUser", "ROLE_USER");
//        };
//    }
}
